version: '3'

services:
  web:
   image: 'audax_v2.0-php'
   ports:
   - '8000:8000'
   volumes:
   - ./:/app
   command: php artisan serve --host=0.0.0.0
   environment:
   - DB_HOST=db
   - DB_NAME=dbaudax
   - DB_USER=postgres
   - DB_PASS=postgres
   depends_on:
   - db
  db:
   image: postgres:12.1-alpine
   volumes: 
   - ./data:/data
   ports:
   - "5432:5432"
   environment:
   - POSTGRES_DB=dbaudax
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
